apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdeployment
  labels:
    team: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fronted
  template:
    metadata:
      labels:
        app: fronted
    spec:
      containers:
      - name: go-gin-react-helloworld
        image: cxberat5353/go-gin-react-helloworld:37
        ports:
        - containerPort: 3012